---
- hosts: localhost
  gather_facts: true

  vars:
    my_name: "megatools"
    my_file: "install_megatools"
    module_name: "megatools"

    packages_build:
      - build-essential
      - libglib2.0-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - make
      - gcc
      - coreutils
      - meson
      - ninja-build

    packages:
      - megatools


    templates:
      - { name: "{{ my_file }}.sh", dest: "{{ retronas_root }}/scripts", mode: "0755" }

  tasks:

    - name: "{{ my_name }} - Load RetroNAS config"
      ansible.builtin.include_vars: retronas_vars.yml

    - block:
      - name: "{{ my_name }} - Install distro package"
        ansible.builtin.import_role:
          name: retronas.role.package.latest
      rescue:
        - ansible.builtin.set_fact:
            package_distro: false
        - meta: clear_host_errors

    - block:
      - ansible.builtin.import_role:
          name: retronas.role.package.latest
        vars:
          - packages: "{{ packages_build }}"

      - ansible.builtin.import_role:
          name: retronas.role.templates

      - name: "{{ my_name }} - build source"
        ansible.builtin.command:
          cmd: "{{ retronas_root }}/scripts/{{ my_file }}.sh"
          creates: "/usr/local/bin/megatools"
      when: not package_distro|default(true)

    - ansible.builtin.import_role:
        name: retronas.role.system-config
